# Workflow : build.yml
# Details  :
#   Exports the project as a Godot project.
# See   : 
#   https://github.com/marketplace/actions/godot-ci *
#   https://github.com/marketplace/actions/godot-export
on: 
  push:
    # uncomment to push only on version releases
    # tags:
    #   - "v*"

env:
  GODOT_VERSION: 3.3.4
  EXPORT_NAME: oni-x-matsuri

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:mono-3.3.4 # use 'mono' for C#
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup Godot Mono
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          cd $EXPORT_NAME
          godot -v --export "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows
          path: build/windows